# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers

    working_directory: ~/beta
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            yarn install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: build landing page
          command: |
            yarn build

      - deploy:
          name: deploy landing page
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh -o StrictHostKeyChecking=no circleci@${BOSTONHACKS_IP_ADDR} 'rm -rf /var/www/bostonhacks/build'
              scp -o StrictHostKeyChecking=no -r ~/beta/build circleci@${BOSTONHACKS_IP_ADDR}:/var/www/bostonhacks
            fi

